# Project information
site_name: SCANPLOT
site_author: Carlos Frederico Bastarz
site_description: Site com a documentação e exemplos de uso do SCANPLOT

# Repository
repo_name: cfbastarz/SCANPLOT
repo_url: https://github.com/cfbastarz/SCANPLOT
edit_uri: edit/main/docs/

# Page tree
nav:
  - 'Introdução': 
    - 'Instalação': instalacao.md
    - 'Apresentação': apresentacao.md
  - 'Uso':
    - 'Leitura dos namelists do SCANTEC': Tutorial_SCANPLOT-leitura_namelists.ipynb
    - 'Função get_dataframe': Tutorial_SCANPLOT-get_dataframe.ipynb
    - 'Explorando os dataframes': Tutorial_SCANPLOT-explorando_dataframes.ipynb
  - 'Funções de plotagem do SCANPLOT':
    - 'Introdução': funcoes_plotagem.md
    - 'plot_lines': Tutorial_SCANPLOT-plot_lines.ipynb
    - 'plot_scorecard': Tutorial_SCANPLOT-plot_scorecard.ipynb
    - 'plot_dTaylor': Tutorial_SCANPLOT-plot_dtaylor.ipynb 
    - 'plot_lines_tStudent': Tutorial_SCANPLOT-plot_lines_tstudent.ipynb

#Configuration
theme: 
  name: material
#  name: readthedocs
#  palette:
#    scheme: slate

# Extensions
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - abbr
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

# Plugins
plugins:
  - mkdocs-video
  - search
  - mkdocs-jupyter:
      theme: dark
