# Project information
site_name: SCANPLOT
site_author: Carlos Frederico Bastarz
site_description: Site com a documentação e exemplos de uso do SCANPLOT

# Repository
repo_name: cfbastarz/SCANPLOT
repo_url: https://github.com/cfbastarz/SCANPLOT
edit_uri: edit/main/docs/

# Page tree
nav:
  - 'Início': 
    - 'Instalação': instalacao.md
    - 'Introdução': introducao.md
  - 'Uso':
    - 'Leitura dos namelists do SCANTEC': Tutorial_SCANPLOT-leitura_namelists.md
    - 'Função get_dataframe': Tutorial_SCANPLOT-get_dataframe.md
    - 'Explorando os dataframes': Tutorial_SCANPLOT-explorando_dataframes.md
  - 'Funções de plotagem do SCANPLOT':
    - 'Introdução': funcoes_plotagem.md
    - 'plot_lines': Tutorial_SCANPLOT-plot_lines.md
    - 'plot_scorecard': Tutorial_SCANPLOT-plot_scorecard.md
    - 'plot_dTaylor': Tutorial_SCANPLOT-plot_dtaylor.md
    - 'plot_lines_tStudent': Tutorial_SCANPLOT-plot_lines_tstudent.md

#Configuration
theme: 
  name: material
  features:
    - content.tabs.link
#    - navigation.instant
#    - navigation.tracking
#    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
#    - navigation.top
#  name: readthedocs
#  palette:
#    scheme: slate

# Extensions
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - abbr
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
#  - mkdocs-video
  - search
#  - with-pdf
#  - mkdocs-jupyter
#  - mkdocs-jupyter:
#      theme: dark
